name: food_app_test_001
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  speech_to_text:
  permission_handler:
  pod_player: ^0.2.2
  flutter_tts: ^3.2.2
  dart_openai: ^5.1.0
  envied: 
  envied_generator:
  audioplayers: ^6.0.0
  path_provider: 



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: 
  

flutter:
  uses-material-design: true
